### ISSUE TITLE
Remove /r/'s from subreddit titles and descriptions

### ISSUE THREAD

**Issue by Boriss** [reddit/reddit-mobile#41]
Right now on h.reddit.com, link descriptions include /r/ in the line and titles include /r/ in the title.  These should be removed, such that only the name of the subreddit is visible.

This has always been in the spec, for a few reasons:

* Unnecessary.  The "/r/" may have historical meaning to current redditors, but it gives no extra information nor context about the subreddit, except to identify it as historically included "/r/" in the URL
* "Safe Hands."  User testing has, unsurprisingly, shown that new users see the /r/ and confusing at best and a bug at worst.  By removing it, we remove the risk of simply implying the site doesn't work.
* Only meaningful as an "in-joke."  There's no explanation or context around /r/, meaning it only serves current users.  By removing it, we're serving new and old users by describing subreddits as simply as possible.  By including it, we're giving a nod to users already "in the know" while potentially confusing newer users
* Saves horizontal space, meaning longer subreddits are more likely to have all letters included
* More readable, as only the parse-able name of the subreddit is visible, no extra characters
* Consistent with reddit app and style guide.  This one's a big one - we want to be similar across platforms, and this decision was made long ago for reddit app, for the same reasons listed above

PS: Jack, I know we talked about this Monday, and I apologize that I didn't realize that pull request (https://github.com/reddit/reddit-mobile/pull/37) included /r/ in subreddit titles

**Comment by Boriss** [comment]
Examples of areas on mobile site without /r/:

![mobileflow04](https://cloud.githubusercontent.com/assets/569650/6800710/56401cb6-d1de-11e4-8fb1-c947f7cb4b7c.png)
![subreddit_metadata_01](https://cloud.githubusercontent.com/assets/569650/6800711/5644bbae-d1de-11e4-9ad0-5428ed1f243a.png)
![subredditmenus01](https://cloud.githubusercontent.com/assets/569650/6800712/5644be74-d1de-11e4-87d5-1daa5740f516.png)

**Comment by Boriss** [comment]
Subreddit title with /r/: 

![screen shot 2015-03-24 at 4 28 18 am](https://cloud.githubusercontent.com/assets/569650/6800750/a8f5296a-d1de-11e4-9429-0b95d38bc54a.png)

**Comment by spladug** [comment]
Some arguments _for_ /r/ (and somewhat less /u/).

* /r/ and /u/ is used already by many redditors in comments. These comments are visible on mobile web.  By not being consistent, we may increase confusion (why is it /r/science here but just science there?).
* This isn't just a design decision for mobile web, it's a company-wide product decision. How should we be communicating the concept of a subreddit and what they're called.  This would apply to reddit.com, mobile apps, mobile web, our human communications, amplify not to mention the impact on the way redditors themselves speak of the subreddits (should mods no longer say "welcome to /r/science" in a sticky post?)
* If we are keeping /r/ elsewhere, can we explain what /r/ means better than we currently do? It seems odd to use new users' initial impressions as the sole metric of worthiness.  Should twitter get rid of hashtags because they look like line noise and might be confusing to new users?

**Comment by umbrae** [comment]
Mentioned in #design, but I also fall on preferring /r/. Happy to make some
arguments too if we want to weigh them.

**Comment by tdohz** [comment]
+1 to everything @spladug said. 

One other thing to consider is if we can make better use of the subreddit  title - right now this only shows up in /subreddits and in the actual HTML title of the page. Unfortunately because of this it's less consistent than the subreddit name, but often it's just a nicely formatted version of the name, e.g. /r/science has the name "Science". With some prodding to the mods, you _could_ try to see if you can get titles into a more consistent "concise subreddit name" format, so that you can do things like "I am A (/r/iama)".

(also, side process note that you guys should really be using JIRA for issues, not github)

**Comment by ajacksified** [comment]
@tdohz - our team operates the way we find most efficient. This is currently a design discussion within our team that we happily invite external discussion on, but it remains within our domain. Once it becomes an external discussion, things generally move to JIRA.

**Comment by ajacksified** [comment]
Discussed with @Boriss; she's going to organize coming up with a full set of top nav states for topic / user / subreddit / etc to make sure there's no confusion about what varying titles mean, and once that's done and consistent across apps, we'll revisit.

/r/ will be staying, only the title bar is currently in question. @Boriss, please step in and re-open the issue if that's incorrect.

**Comment by Boriss** [comment]
:sunglasses: @designreview

**Comment by Boriss** [comment]
:eyeglasses: @designreview this is a test please ignore
