### ISSUE TITLE
Double-tilde strikethrough markup is ignored in self-posts, wiki pages

### ISSUE THREAD

**Issue by green-flash** [reddit/reddit-mobile#582]
See this post for example

https://m.reddit.com/r/mobileweb/comments/4g58vs/doubletilde_strikethrough_markup_is_ignored_in/

In comments it is rendered correctly, wrapped in a \<del> tag.

**Comment by O4epegb** [comment]
Migth be because Post component using "expandText" property for text content, and Comment component using "body_html" property. Maybe "expandText" lacks this tags somehow? Could not run the app locally, so couldnt test.
The strange thing, that there is no "expandText" in json from server (when checking through devTools), only selftext_html. Could not figure out why it is so.

**Comment by prashtx** [comment]
This should be fixed now, and rendered text should be more consistent across the app. Thanks!

(72939a3a0b782b0eb03c264c56e687535a1b5af5)
